### ISSUE TITLE
English translation improvement for when there is no news.

### ISSUE THREAD

**Issue by hamishmb** [rh-id/a-news-provider#10]
Hi there, and thanks for the great app.

I feel it would make more sense for the app to say "No News" instead of "No Record" when there are no news items to read (eg if you are only displaying unread items).

I will happily submit a merge request if you can give me a pointer for where I'm meant to be looking - I haven't done any Android app development at all.

**Comment by rh-id** [comment]
Hi @hamishmb thanks for the feedback. This label is highly subjective and actually very trivial. I believe irregardless whether it is "No News" or "No Record" user still knows that it means it is empty or no news or items.

You could say it is more make sense to use "No News" while I could say it is more make sense to use "No Record" other people could also come and say "No Article" is more make sense or even "No Items" hence it is very subjective.

There is no compelling reason to change this label.

**Comment by hamishmb** [comment]
Oh yeah I agree it's not important. But would you be interested in a merge request for this and a few other similar things?

**Comment by rh-id** [comment]
No im not interested in merge request like this.

**Comment by hamishmb** [comment]
Okay, I'll close this now then.
