### ISSUE TITLE
Bug: "None" Changes to "Unread" Upon Restart

### ISSUE THREAD

**Issue by HonestAbe7** [rh-id/a-news-provider#15]
I found that changing the filter to "None" changes back to "Unread" when restarting the app. I would like to see all my feeds on one screen.

**Comment by rh-id** [comment]
This is not a bug. The whole list are reloaded when the app restarted.

**Comment by HonestAbe7** [comment]
Well, I just tried it and it is back to saying, "No Record" when I changed the filter to "None" and restarted.

**Comment by rh-id** [comment]
@HonestAbe7 I dont understand your explanation, could you explain step by step? how you restart the app?

**Comment by HonestAbe7** [comment]
I just close the app by clearing all app opened like on a windows PC. I use a navigation button that shows open apps.

**Comment by rh-id** [comment]
and as per what I stated it was not a bug
