### ISSUE TITLE
Sync less than hourly 

### ISSUE THREAD

**Issue by orschiro** [rh-id/a-news-provider#19]
Hi

Love the simplicity of your reader!

Could you add sync intervals less than hourly?

For example every 5,15,30,45 minutes.

Thanks!

**Comment by rh-id** [comment]
Hi, No

**Comment by orschiro** [comment]
Bummer, why?

Is it too complicated to add?

Jul 1, 2023 1:31:29 AM rh-id ***@***.***>:

**Comment by HonestAbe7** [comment]
I do this as being useful but we can't twist the arm of the developer if not willing to do this. I do enjoy the refresh button at the top. 😁
