### ISSUE TITLE
Can't Add Feeds

### ISSUE THREAD

**Issue by HonestAbe7** [rh-id/a-news-provider#2]
I just tried your new app on F-Droid and it wouldn't let me add any RSS feeds.

**Comment by rh-id** [comment]
Hi,

Please provide more details on how you use the app. What button you click? What screen is shown? What error message is shown?

Also please provide the following:
1. Screenshots of the error
2. Operating system version that you use
3. Device that you use

**Comment by HonestAbe7** [comment]
I cant give you a screenshot because the error goes away too quickly. It says feed add error with a long string. I am using Android 10 on an LG device.

Dec 7, 2021 6:56:55 PM rh-id ***@***.***>:

> Hi,
> 
> Please provide more details on how you use the app. What button you click? What screen is shown? What error message is shown?
> 
> Also please provide the following:
> 
1. > Screenshots of the error
2. > Operating system version that you use
3. > Device that you use

**Comment by rh-id** [comment]
Please provide screenshot of the log file. Go to Settings - Log File

**Comment by HonestAbe7** [comment]
Here is the screenshot:
 [cid:eu.faircode.email.75]

Dec 7, 2021 7:40:45 PM rh-id ***@***.***>:

**Comment by HonestAbe7** [comment]
![Screenshot_20211207-195447](https://user-images.githubusercontent.com/88217236/145129437-e74d91fb-a4e8-4c06-9c3f-14d9bc4a3e4e.png)

**Comment by rh-id** [comment]
What is the full URL you type in?

**Comment by HonestAbe7** [comment]
http://www.redstate.com/feed/

I can't add any feed as I tried multiple ones.

Dec 7, 2021 7:59:42 PM rh-id ***@***.***>:

**Comment by rh-id** [comment]
Try `https://redstate.com/feed` instead. Http not allowed in android devices starting from android 8

**Comment by HonestAbe7** [comment]
Thanks. It works now! 👍

Dec 7, 2021 8:22:27 PM rh-id ***@***.***>:
