### ISSUE TITLE
Corrupt File When Exporting OPML File

### ISSUE THREAD

**Issue by HonestAbe7** [rh-id/a-news-provider#25]
I just tried to import the OPML file created by this app, Exporting it, into 3 different other feeders. Please fix this. Thanks

**Comment by rh-id** [comment]
You should request support ticket to those 3 different app and ask why the OPML doesnt work. after you received the feedback including which part causes the issue in every app then you could open another issue here. you cant just open an issue and then said it doesnt work with another app without any details.
