### ISSUE TITLE
Layout options

### ISSUE THREAD

**Issue by Donkey-Doug** [rh-id/a-news-provider#3]
Make it possible to make some changes to the layout, like:

-    Make it possible to hide image and only show text.
-    Image on the left or right.
-    Large card-style centered image with the headline either above or below the image.
-    Large card-style centered image with the headline on top of the image. Add shadow around white text to remain readable.
-    Change padding around images. Let the user choose vertical and horizontal padding. Make it possible for content to reach the sides of the screen (0 horizontal padding) and completely eliminate the space between articles (0 vertical padding).
-    Two or more columns of articles. Particularly useful for landscape mode.
-    Hide/show the source.
-    Customize source name shown for every feed.
-    Disable/enable swipe left/right on article. The feature mark a read can be implemented with a longpress.
-    Hide/show preview text

**Comment by rh-id** [comment]
Thank you for your very constructive feedback. That is a very long list of complicated feature to implement.

The reason I create this app is for the usage to be as simple as possible, and also showing off my new framework and library. Making user tweak the UI itself on that level seemed to kill the purpose of making it simple. Regardless, I will consider some of these ideas in mind.

I believe there are some RSS apps that had implement some of these feature, you might try those if you urgently need these features.

**Comment by shuvashish76** [comment]
Long list.
@rh-id please turn on "Discussion" option for this repo on GitHub, and convert this issue to a discussion.
Extract separate issues (which you think easier/possible to implement) from the discussion.

**Comment by shuvashish76** [comment]
I understand, it's a demo app & IG just a hobby project (for learning purpose).

> I dont plan to implement all of these ideas

Totally upto you, I just mentioned my idea. Thanks :)
