### ISSUE TITLE
Import option

### ISSUE THREAD

**Issue by shuvashish76** [rh-id/a-news-provider#4]
Please support import `.opml` files.
Useful to move from other RSS readers.

**Comment by rh-id** [comment]
Hi, this app support .opml file. Open the file using this app to import the feed.

**Comment by shuvashish76** [comment]
How to import?

![Screenshot_2022-02-11-14-02-27](https://user-images.githubusercontent.com/48226312/153560819-03789bef-6bc0-49f8-8db6-c492da019d43.jpeg)

> Open the file using this app to import the feed.

As in from filemanager? I don't think it's the conventional method for most users 😐
