### ISSUE TITLE
Feature request: Add a button to return to aggregate feed

### ISSUE THREAD

**Issue by christopherlam888** [rh-id/a-news-provider#8]
Upon opening the app, articles from all feeds are displayed together. However, once clicking on a specific feed, I cannot return to the aggregate view. A button to return to this view would be a much appreciated UI improvement. As of now, I am closing and reopening the app as a workaround.

**Comment by rh-id** [comment]
Hi, thanks for the idea. Instead of adding a button, I will make the feeds selection to be removed if selected feed is tapped.

**Comment by christopherlam888** [comment]
That's a great solution, thanks!

**Comment by rh-id** [comment]
Fixed on d03de5b1da2bc04cdb476d7d82d6c0b51803ad22
This will be included in next version
