### ISSUE TITLE
RSS are not adding 

### ISSUE THREAD

**Issue by solomonrajan** [rh-id/a-news-provider#9]
I've attached log file, the issue is that while I add rss none of them are adding into app. The error shows is:
add error
java.lang.RuntimeException: "Error: com.android.volley.NoConnection Error: java.io.lOException: unexpected end of stream on com.android.okhttp .Address@46e7a1b2"
[app.log](https://github.com/rh-id/a-news-provider/files/9125290/app.log)

**Comment by rh-id** [comment]
Hi, ensure that you have internet connection. Also ensure that your RSS link is reachable.

**Comment by HonestAbe7** [comment]
Same issue here except is says,"Added RSS:0" on the bottom.

**Comment by rh-id** [comment]
@HonestAbe7 your case is different. please create new issue and provide rss link that you add and share the log file. The app doesn't have feature to add file
